### ISSUE TITLE
It crashes due to the balance between thread release and Shutdown()

### ISSUE THREAD

**Issue by manboryoma** [sammyfreg/netImgui#12]
**Describe the bug**

netimugiLib を自分のプロジェクト(Win64)に実装しようとした際、
プログラムを終了する際にクラッシュすることがあり調べてみたところ、
原因はCommunicationsClient()/CommunicationsHost()でpClientが不定でエラーとなっていました。
Shutdown()でスレッドの終了を待っていないのが原因だと思うのですがいかがでしょうか？
(英語が苦手なので、日本語をGoogle翻訳で変更したものを下記に記載させていただきます)

----

When I tried to implement netimugiLib in my project (Win64)
When I checked it, it sometimes crashed when quitting the program.
The cause was CommunicationsClient () / CommunicationsHost () where pClient was undefined and an error occurred.
I think it's because Shutdown () isn't waiting for the thread to finish.
(Since I am not good at English, I will describe the Japanese translated by Google Translate below)

**Desktop (please complete the following information):**
 - OS : Windows
 - Build : VisualStudio2019

**Additional context**

Github での作法などはわかっていないため、報告などに問題があれば申し訳ありません。

----

I don't know how to do it on Github, so I'm sorry if there is a problem with the report.

**Comment by sammyfreg** [comment]
I have seen similar shutdown issue before. I will try to reproduce the issue and fix it.

> 以前にも似たようなシャットダウンの問題を見たことがあります。私は問題を再現し、それを修正してみます。

**Comment by sammyfreg** [comment]
Also, you might want to try the 'dev' branch, there were some shutdown issues already solved in it. Let me know if it takes care of your problem.

> また、'dev' ブランチを試してみるのもいいかもしれません。これで問題が解決されたら教えてください。

**Comment by manboryoma** [comment]
dev ブランチにしてみましたが、低確率ですが再現しました。
もう一度調査してみたのですが、NetImgui_App.cpp Line:323の[if( !gpClientInfo )]は[if( gpClientInfo )]ではないでしょうか？

---

I tried to make it a dev branch, but it was reproduced with a low probability.
I investigated it again, but isn't [if (! GpClientInfo)] in NetImgui_App.cpp Line: 323 [if (gpClientInfo)]?

**Comment by sammyfreg** [comment]
It should be valid. In 'Startup()' I create the initial client data if not created. In every other functions, I need to skip it if data hasn't been initialized yet.

> 有効なはずです。Startup()では、初期クライアントデータが作成されていない場合は、初期クライアントデータを作成しています。他の関数では、データがまだ初期化されていない場合はスキップする必要があります。

**Comment by manboryoma** [comment]
Startup() は [if( !gpClientInfo )] で正しいと思いますが、Shutdown() が  [if( !gpClientInfo )] だと、gpClientInfoの開放などが動作しないと思います… 

----
I think Startup () is correct with [if (! GpClientInfo)], but if Shutdown () is [if (! GpClientInfo)], I don't think delete gpClientInfo etc. works ...

**Comment by sammyfreg** [comment]
I was unable to get a single crash, after closing the program 'SampleBasic' in 'dev' branch, 10 times each in various configuration : I was unable to get a single crash, after closing the program 'SampleBasic' in 'dev' branch, 10 times each in various configuration : 'Debug', 'Release', 'not connected', 'connected', 'waiting for connection'.  'Shutdown()' function now need a 'bool' parameter to not return until all communications have been terminated, this might help with your issue too. 

>dev'ブランチの'SampleBasic'プログラムを'Debug'、'Release'、'not connected'、'connected'、'waiting for connection'と様々な設定で10回ずつ終了させても、一度もクラッシュすることはありませんでした。 Shutdown()' 関数は、すべての通信が終了するまで戻らないように 'bool' パラメータを必要とするようになりました。

**Comment by manboryoma** [comment]
申し訳ありません。
mastar から dev ブランチに正しく置き換わっていませんでした。
dev ブランチを適応し、テストを繰り返しましたが現在のところ発生しておりません。
(適応前なら発生している回数では発生しておりません)

----

I'm sorry.
The mastar wasn't properly replaced with the dev branch.
I adapted the dev branch and repeated the tests, but it hasn't happened so far.
(Before adaptation, it does not occur as many times as it occurs)
