### ISSUE TITLE
Opengl2 backend

### ISSUE THREAD

**Issue by A3Wypiok** [sammyfreg/netImgui#20]
I would like to use netImgui on Linux with glfw and opengl2 but the displayed texture of client app is bad.
Client app and netimgui server are on the same machine (localhost).

Here is my client app :

<p align="center">
  <img src="https://user-images.githubusercontent.com/6884897/133610975-7514c945-4beb-4049-a15a-f69d7ce179a3.png" width="500">
</p>

with this loop :
```C++
while(!glfwWindowShouldClose(m_window))
{
    glfwPollEvents();

    glClear(GL_COLOR_BUFFER_BIT);

    ImGuiIO *io = &::ImGui::GetIO(); (void)io;
    glViewport(0, 0, (int)io->DisplaySize.x, (int)io->DisplaySize.y);

    ImGui_ImplOpenGL2_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ::NetImgui::NewFrame();

    if (NetImgui::IsConnected()) {
    } else // No connection
    {
        //-------------------------------------------------------------------------------------
        if (ImGui::BeginMenu("[ Connect to ]"))
        //-------------------------------------------------------------------------------------
        {
            if (ImGui::Button("Connect", ImVec2(ImGui::GetContentRegionAvailWidth(), 0))) {
                NetImgui::ConnectToApp(zAppName, sServerHostname, sServerPort);
            }
            ImGui::EndMenu();
        }
    }

    if( ImGui::Begin("Sample Basic 2", nullptr) )
    {
        ImGui::TextColored(ImVec4(0.1, 1, 0.1, 1), "Basic demonstration of netImgui code integration.");
        ImGui::TextWrapped("Create a basic Window with some text.");
        ImGui::NewLine();
        ImGui::TextColored(ImVec4(0.1, 1, 0.1, 1), "Where are we drawing: ");
        ImGui::SameLine();
        ImGui::TextUnformatted(NetImgui::IsDrawingRemote() ? "Remote Draw" : "Local Draw");
        ImGui::NewLine();
        ImGui::TextColored(ImVec4(0.1, 1, 0.1, 1), "Filler content");
        ImGui::TextWrapped(
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        ImGui::End();
    }

    ::NetImgui::EndFrame();
    ImGui_ImplOpenGL2_RenderDrawData(::ImGui::GetDrawData());

    glfwMakeContextCurrent(m_window);
    glfwSwapBuffers(m_window);
}
```

On the server side i created `NetImguiServer_HAL_opengl2.cpp` :

```C++
//=================================================================================================
// Source file handling renderer specific commands needed by NetImgui server.
// It complement the rendering backend with a few more functinoalities.
//=================================================================================================
#include <GL/glew.h>
#include "imgui_impl_opengl2.h"

#include "NetImguiServer_App.h"
#include "NetImguiServer_RemoteClient.h"
#include <Private/NetImgui_Shared.h>

namespace NetImguiServer {
namespace App {

//=================================================================================================
// HAL RENDER DRAW DATA
// The drawing of remote clients is handled normally by the standard rendering backend,
// but output is redirected to an allocated client texture  instead default swapchain
//=================================================================================================
    void HAL_RenderDrawData(RemoteClient::Client& client, ImDrawData* pDrawData)
    {
        if( client.mpHAL_AreaRT )
        {
            glBindFramebuffer(GL_FRAMEBUFFER, (GLuint)(intptr_t)client.mpHAL_AreaRT);
            glClearColor(
                    client.mBGSettings.mClearColor[0] * client.mBGSettings.mClearColor[3],
                    client.mBGSettings.mClearColor[1] * client.mBGSettings.mClearColor[3],
                    client.mBGSettings.mClearColor[2] * client.mBGSettings.mClearColor[3],
                    client.mBGSettings.mClearColor[3]);
            glClear(GL_COLOR_BUFFER_BIT);

            {
                NetImgui::Internal::ScopedImguiContext scopedCtx(client.mpBGContext);
                ImGui_ImplOpenGL2_RenderDrawData(ImGui::GetDrawData());
            }
            if (pDrawData)
            {
                ImGui_ImplOpenGL2_RenderDrawData(pDrawData);
            }

            glBindFramebuffer(GL_FRAMEBUFFER, 0);
        }
    }

//=================================================================================================
// HAL CREATE RENDER TARGET
// Allocate RenderTargetView / TextureView for each connected remote client. 
// The drawing of their menu content will be outputed in it, then displayed normally 
// inside our own 'NetImGui application' Imgui drawing
//=================================================================================================
    bool HAL_CreateRenderTarget(uint16_t Width, uint16_t Height, void*& pOutRT, void*& pOutTexture)
    {
        HAL_DestroyRenderTarget(pOutRT, pOutTexture);

        GLuint pTextureView = 0u;
        glGenTextures(1, &pTextureView);
        glBindTexture(GL_TEXTURE_2D, pTextureView);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

//        glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, Width, Height, 0, GL_RGBA, GL_UNSIGNED_BYTE, NULL);
		
        GLuint pRenderTargetView = 0u;
        glGenFramebuffers(1, &pRenderTargetView);
        glBindFramebuffer(GL_FRAMEBUFFER, pRenderTargetView);

        //Attach 2D texture to this FBO
        glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, pTextureView, 0);

        GLenum status;
        status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
        switch(status)
        {
            case GL_FRAMEBUFFER_COMPLETE:
                printf("good\n");
                break;
            default:
                printf("error\n");
                return false;
        }

        glBindTexture(GL_TEXTURE_2D, 0);

        // switch back to window-system-provided framebuffer
        glBindFramebuffer(GL_FRAMEBUFFER, 0);

        pOutRT      = reinterpret_cast<void*>(pRenderTargetView);
        pOutTexture = reinterpret_cast<void*>(pTextureView);

        return true;
    }

//=================================================================================================
// HAL DESTROY RENDER TARGET
// Free up allocated resources tried to a RenderTarget
//=================================================================================================
    void HAL_DestroyRenderTarget(void*& pOutRT, void*& pOutTexture)
    {
        if(pOutRT)
        {
            GLuint pRT = (GLuint)(intptr_t)pOutRT;
            glDeleteFramebuffers(1, &pRT);
        }

        if (pOutTexture)
        {
            GLuint pTexture = (GLuint)(intptr_t)pOutTexture;
            glDeleteTextures(1, &pTexture);
        }
    }

//=================================================================================================
// HAL CREATE TEXTURE
// Receive info on a Texture to allocate. At the moment, 'Dear ImGui' default rendering backend
// only support RGBA8 format, so first convert any input format to a RGBA8 that we can use
//=================================================================================================
    bool HAL_CreateTexture(uint16_t Width, uint16_t Height, NetImgui::eTexFormat Format, const uint8_t* pPixelData /* TODO unsigned char */ , ServerTexture& OutTexture)
    {
        HAL_DestroyTexture(OutTexture);

        // Convert all incoming textures data to RGBA8
        uint32_t* pPixelDataAlloc = nullptr;
        if(Format == NetImgui::eTexFormat::kTexFmtA8)
        {
            pPixelDataAlloc = NetImgui::Internal::netImguiSizedNew<uint32_t>(Width*Height*4);
            for (int i = 0; i < Width * Height; ++i){
                pPixelDataAlloc[i] = 0x00FFFFFF | (static_cast<uint32_t>(pPixelData[i])<<24);
            }
            pPixelData = reinterpret_cast<const uint8_t*>(pPixelDataAlloc);
        }
        else if (Format == NetImgui::eTexFormat::kTexFmtRGBA8)
        {
            printf("format kTexFmtRGBA8\n");
        }
            // Unsupported format
        else
        {
            printf("unsupported format\n");

            return false;
        }

        // Save state
        GLint last_texture;
        glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture);

        GLuint texture = 0u;
        glGenTextures(1, &texture);

        glBindTexture(GL_TEXTURE_2D, texture);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

        //glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, Width, Height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pPixelData);

        OutTexture.mSize[0]         = Width;
        OutTexture.mSize[1]         = Height;
        OutTexture.mpHAL_Texture    = (void*)(intptr_t)(texture);

        // Restore state
        glBindTexture(GL_TEXTURE_2D, last_texture);

        if(pPixelDataAlloc)
        {
            NetImgui::Internal::netImguiDeleteSafe(pPixelDataAlloc);
        }

        return true;
    }

//=================================================================================================
// HAL DESTROY TEXTURE
// Free up allocated resources tried to a Texture
//=================================================================================================
    void HAL_DestroyTexture(ServerTexture& OutTexture)
    {
        if (OutTexture.mpHAL_Texture)
        {
            GLuint texture = (GLuint)(intptr_t)OutTexture.mpHAL_Texture;
            glDeleteTextures(1, &texture);
            memset(&OutTexture, 0, sizeof(OutTexture));
        }
    }

} // namespace App
} // namespace NetImguiServer
```

My first problem was that the font texture was not correctly displayed :

<p align="center">
  <img src="https://user-images.githubusercontent.com/6884897/133614949-17afa9c6-fe76-4478-ac84-e26c8ec6672c.png" width="500">
</p>

This is because the function `HAL_CreateTexture` is not called from the main thread. This other thread doesn't have opengl context so `glGenTextures` call fails.

I have found a workaround and now it works :
<p align="center">
  <img src="https://user-images.githubusercontent.com/6884897/133616699-be47c281-b107-42ad-8c97-2048e3d81075.png" width="500">
</p>

But when i create two imgui "Sample Basic" window (the "Debug" window disappear when client is connected to server) :
<p align="center">
  <img src="https://user-images.githubusercontent.com/6884897/133617473-369f634f-611f-4cc7-8b35-1c20eb47e564.png" width="500">
</p>

now i have bad texture displayed on server (client app on left and netimgui server on right) :

<p align="center">
  <img src="https://user-images.githubusercontent.com/6884897/133619404-364c11f4-d829-4c42-9ac5-e57dcfadc8cd.gif">
</p>

I have tried with netimgui 1.6 and imgui 1.80, 1.84.2 and docking branch and i have the same results.

**Comment by sammyfreg** [comment]
I'm glad to see that adding an API abstraction layer to allow the server to run on other OS, was of interest to someone.

Haven't touched OpenGL in a while, but I can try to take your code and compile with OpenGl on Windows, and see what's happening. I'm mostly relying on the Dear ImGui rendering backend to display content. This will be in the coming weeks.

If you could send me a RenderDoc capture, I could also have a quick look and have a better idea of what's going on.

**Comment by A3Wypiok** [comment]
I started working with opengl only a few months ago so i didn't know about RenderDoc.
It seams that RenderDoc support opengl from 3.2 up to 4.6 and i need to use opengl 2 :cry: .

But i changed my client app and netimgui server to use opengl 3. Client works but the server crashed. It crashed in function `HAL_RenderDrawData` on this lines :

```C++
{
    NetImgui::Internal::ScopedImguiContext scopedCtx(client.mpBGContext);
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
}
```

The function `ImGui_ImplOpenGL3_RenderDrawData` calls `ImGui_ImplOpenGL3_GetBackendData` that returns null pointer (because `ImGui::GetIO().BackendRendererUserData` is null).

Here is the content of `client.mpBGContext` and you can see that all Backend* members are null :
<p align="center">
  <img width="200" src="https://user-images.githubusercontent.com/6884897/133664853-b1767a07-1b39-4173-8968-7b079dd03220.png">
</p>

If i comment this two lines the server doesn't crash and the client texture displayed on netimgui server is good. No texture problems like with opengl 2. But as i commented this two lines i don't have the background texture.

<p align="center">
  <img width="500" src="https://user-images.githubusercontent.com/6884897/133667444-b498eb08-a137-4335-acea-a814e47fe0e4.png">
</p>

I tried to comment this two lines with opengl 2 but nothing changed, the displayed texture is still bad.

**Comment by sammyfreg** [comment]
this suggest that some of the Initialization wasn't completely done. As mentioned, the OS/Graphics support mostly comes directly from the Dear ImGui samples provided, with some tweak (that are annotated).

As a quick tip for your current problem, compare what's different between my `NetImguiServer_App_win32dx11.cpp` and the original main.cpp from Dear Imgui. In your case, `(DearImGuiFolder)\examples\example_glfw_opengl3\main.cpp`, the missing backend initialisation can problably be found there (my was from the DX11 sample).

**Comment by A3Wypiok** [comment]
I'm already using the example files from imgui and just added the lines with @SAMPLE_EDIT tag.

I see that in `NetImguiServer_App.cpp` the function `CreateDrawData` set flags :

```C++
pCmdList->Flags = ImDrawListFlags_AllowVtxOffset |
    ImDrawListFlags_AntiAliasedLines |
    ImDrawListFlags_AntiAliasedFill |
    ImDrawListFlags_AntiAliasedLinesUseTex;
```

The flag `ImDrawListFlags_AllowVtxOffset` is only supported with OpenGL 3.2+ as i found in the imgui `ImGui_ImplOpenGL3_Init`: 
```
#ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET
    if (bd->GlVersion >= 320)
        io.BackendFlags |= ImGuiBackendFlags_RendererHasVtxOffset;  // We can honor the ImDrawCmd::VtxOffset field, allowing for large meshes.
#endif
```

Also i find a note in `NetImgui_CmdPackets_DrawFrame.h` about ImguiVert `Note: Keep these 4 constants in sync with 'ImguiVS.hlsl'` but i don't have this file. I don't know what it is for and is it important ?

I'm not using shaders but imgui opengl3 banckend initialize one in function `ImGui_ImplOpenGL3_CreateDeviceObjects` where `ImGui_ImplOpenGL2_CreateDeviceObjects` not.

Does one of these differences could explain  why there is problem with opengl2 and none with opengl3 ?

**Comment by sammyfreg** [comment]
>The flag ImDrawListFlags_AllowVtxOffset is only supported with OpenGL 3.2+ as i found in the imgui 
This might be a problem for API that do not support it, I'll look into it and see if it can be gotten around, I do rely on offsets in my rendering... Thanks for finding out about it.

> Also i find a note in NetImgui_CmdPackets_DrawFrame.h about ImguiVert Note: Keep these 4 constants in sync with 'ImguiVS.hlsl' but i don't have this file. I don't know what it is for and is it important ?
This was from older NetImguiServer code, when I was using my own vertex shader. I now convert back the vertices back to 'normal' values and use the stock Dear Imgui sample shaders, so this is not a problem.

> I'm not using shaders but imgui opengl3 banckend initialize one in function ImGui_ImplOpenGL3_CreateDeviceObjects where ImGui_ImplOpenGL2_CreateDeviceObjects not.
If you are using the Dear Imgui samples code straight, with the few adjustments I tagged in my code, it _should_ work as is. Obviously it is not, so over the coming weeks, when I have some free time, I'll try to also compile the NetImguiServer using the OpenGL2/3 code and see what are the problems for myself (under Windows).

**Comment by sammyfreg** [comment]
I managed to compiled with GL3 and run in Windows, but still have to fix some texture issues. I used most of the GL you already made for the HAL interface.

I had a question regarding the GL2 support. Do you really need to have the NetImguiServer run with GL2? Just to be sure, the server doesn't need to be running the same renderer backend than the client code, and I find it surprising that GL3 wouldn't be supported under a regular linux PC distro.

**Comment by sammyfreg** [comment]
Ok, I am able to successfully render in GL3.
![image](https://user-images.githubusercontent.com/19142627/133914027-7abe4230-d1c2-4f1f-9ce5-3a5689fe7aa9.png)

There's still some things I want to improve before I submit the code, but here's the GL HAL code so far. Let me know if it helps you. It's not very different from the code you wrote, with the addition of deferred texture creation/destruction. Maybe the issues is more tied to the OS, or the version of OpenGL?

```c++
//=================================================================================================
// Source file handling renderer specific commands needed by NetImgui server.
// It complement the rendering backend with a few more functionalities.
//=================================================================================================
#include "NetImguiServer_App.h"

#if HAL_API_PLATFORM_GLFW_GL3

#include <array>
#include "NetImguiServer_RemoteClient.h"
#include <imgui_impl_opengl3.h>
#include <GL/glcorearb.h>
#include <GL/gl3w.h>

namespace NetImguiServer { namespace App
{

//=================================================================================================
// 2 Ring buffer to defer texture creation/destruction so that it
// is done on the main thread
//=================================================================================================
struct PendingTextureCreate
{
	uint16_t				mWidth;
	uint16_t				mHeight; 
	NetImgui::eTexFormat	mFormat; 
	uint32_t*				mpPixelData;
	ServerTexture*			mpOutTexture;
};

constexpr uint64_t kPendingCount = 128;
static std::array<PendingTextureCreate,kPendingCount>	sPendingCreateTextures;
static std::atomic_uint64_t								sPendingCreateReadIndex		= 0;
static std::atomic_uint64_t								sPendingCreateWriteIndex	= 0;

static std::array<ServerTexture*,kPendingCount>			sPendingDestroyTextures;
static std::atomic_uint64_t								sPendingDestroyReadIndex	= 0;
static std::atomic_uint64_t								sPendingDestroyWriteIndex	= 0;

//=================================================================================================
// HAL RENDER DRAW DATA
// The drawing of remote clients is handled normally by the standard rendering backend,
// but output is redirected to an allocated client texture  instead default swapchain
//=================================================================================================
void HAL_RenderDrawData(RemoteClient::Client& client, ImDrawData* pDrawData)
{
	if( client.mpHAL_AreaRT )
	{
		//-----------------------------------------------------------------------------------------
		// Destroy all pending textures
		//-----------------------------------------------------------------------------------------
		while (sPendingDestroyReadIndex < sPendingDestroyWriteIndex) {
			ServerTexture* pServerTexture	= sPendingDestroyTextures[(sPendingDestroyReadIndex++) % kPendingCount];
			GLuint pTexture = static_cast<GLuint>(reinterpret_cast<uint64_t>(pServerTexture));
			glDeleteTextures(1, &pTexture);
			memset(pServerTexture, 0, sizeof(ServerTexture));
		}
				 
		//-----------------------------------------------------------------------------------------
		// Create all pending textures
		//-----------------------------------------------------------------------------------------
		GLint last_texture;
		glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture); // Save state
		while (sPendingCreateReadIndex < sPendingCreateWriteIndex) {
			PendingTextureCreate& textureInfo = sPendingCreateTextures[sPendingCreateReadIndex%kPendingCount];
			
			// Release previous texture
			if( textureInfo.mpOutTexture->mpHAL_Texture )
			{
				GLuint pTexture = static_cast<GLuint>(reinterpret_cast<uint64_t>(textureInfo.mpOutTexture->mpHAL_Texture));
				glDeleteTextures(1, &pTexture);
				memset(textureInfo.mpOutTexture, 0, sizeof(ServerTexture));
			}

			// Create new texture
			GLuint texture = 0u;
			glGenTextures(1, &texture);

			GLenum error = glGetError();
			(void)error;

			glBindTexture(GL_TEXTURE_2D, texture);
			glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
			glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

			//glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
			glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, textureInfo.mWidth, textureInfo.mHeight, 0, GL_RGBA, GL_UNSIGNED_BYTE, textureInfo.mpPixelData);

			textureInfo.mpOutTexture->mSize[0]		= textureInfo.mWidth;
			textureInfo.mpOutTexture->mSize[1]		= textureInfo.mHeight;
			textureInfo.mpOutTexture->mpHAL_Texture	= reinterpret_cast<void*>(static_cast<uint64_t>(texture));
			NetImgui::Internal::netImguiDeleteSafe(textureInfo.mpPixelData);
			
			++sPendingCreateReadIndex;
		}
		glBindTexture(GL_TEXTURE_2D, last_texture); // Restore state

		//-----------------------------------------------------------------------------------------
		// Render the Client and Server content
		//-----------------------------------------------------------------------------------------
		glBindFramebuffer(GL_FRAMEBUFFER, static_cast<GLuint>(reinterpret_cast<uint64_t>(client.mpHAL_AreaRT)));
		glClearColor(client.mBGSettings.mClearColor[0], client.mBGSettings.mClearColor[1], client.mBGSettings.mClearColor[2], client.mBGSettings.mClearColor[3]);
		glClear(GL_COLOR_BUFFER_BIT);
		{
			NetImgui::Internal::ScopedImguiContext scopedCtx(client.mpBGContext);
			ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
		}
		if (pDrawData)
		{
			ImGui_ImplOpenGL3_RenderDrawData(pDrawData);
		}
		glBindFramebuffer(GL_FRAMEBUFFER, 0);
	}
}

//=================================================================================================
// HAL CREATE RENDER TARGET
// Allocate RenderTargetView / TextureView for each connected remote client. 
// The drawing of their menu content will be outputed in it, then displayed normally 
// inside our own 'NetImGui application' Imgui drawing
//=================================================================================================
bool HAL_CreateRenderTarget(uint16_t Width, uint16_t Height, void*& pOutRT, void*& pOutTexture)
{
	HAL_DestroyRenderTarget(pOutRT, pOutTexture);

    GLuint pTextureView = 0u;
    glGenTextures(1, &pTextureView);
    glBindTexture(GL_TEXTURE_2D, pTextureView);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

//    glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, Width, Height, 0, GL_RGBA, GL_UNSIGNED_BYTE, NULL);
		
    GLuint pRenderTargetView = 0u;
    glGenFramebuffers(1, &pRenderTargetView);
    glBindFramebuffer(GL_FRAMEBUFFER, pRenderTargetView);

    //Attach 2D texture to this FBO
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, pTextureView, 0);

    GLenum status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
	bool bSuccess = status == GL_FRAMEBUFFER_COMPLETE;

	// Unbind resources
    glBindTexture(GL_TEXTURE_2D, 0);
    glBindFramebuffer(GL_FRAMEBUFFER, 0); 

	if( bSuccess ){
		pOutRT      = reinterpret_cast<void*>(static_cast<uint64_t>(pRenderTargetView));
		pOutTexture = reinterpret_cast<void*>(static_cast<uint64_t>(pTextureView));
		return true;
	}
    return false;
}

//=================================================================================================
// HAL DESTROY RENDER TARGET
// Free up allocated resources tried to a RenderTarget
//=================================================================================================
void HAL_DestroyRenderTarget(void*& pOutRT, void*& pOutTexture)
{
	if(pOutRT)
	{
		GLuint pRT	= static_cast<GLuint>(reinterpret_cast<uint64_t>(pOutRT));
		pOutRT		= nullptr;
		glDeleteFramebuffers(1, &pRT);
	}
	if(pOutTexture)
	{
		GLuint pTexture = static_cast<GLuint>(reinterpret_cast<uint64_t>(pOutTexture));
		pOutTexture		= nullptr;
		glDeleteTextures(1, &pTexture);
	}
}

//=================================================================================================
// HAL CREATE TEXTURE
// Receive info on a Texture to allocate. At the moment, 'Dear ImGui' default rendering backend
// only support RGBA8 format, so first convert any input format to a RGBA8 that we can use
//=================================================================================================
bool HAL_CreateTexture(uint16_t Width, uint16_t Height, NetImgui::eTexFormat Format, const uint8_t* pPixelData, ServerTexture& OutTexture)
{
	HAL_DestroyTexture(OutTexture);

	// Convert all incoming textures data to RGBA8
	uint32_t* pPixelDataAlloc = NetImgui::Internal::netImguiSizedNew<uint32_t>(Width*Height*4);
	if(Format == NetImgui::eTexFormat::kTexFmtA8)
	{
		for (int i = 0; i < Width * Height; ++i){
			pPixelDataAlloc[i] = 0x00FFFFFF | (static_cast<uint32_t>(pPixelData[i])<<24);
		}
		pPixelData = reinterpret_cast<const uint8_t*>(pPixelDataAlloc);
	}
	else if (Format == NetImgui::eTexFormat::kTexFmtRGBA8)
	{
		memcpy(pPixelDataAlloc, pPixelData, Width*Height*4);
	}	
	else
	{
		// Unsupported format
		return false;
	}

	PendingTextureCreate& textureInfo	= sPendingCreateTextures[sPendingCreateWriteIndex%kPendingCount];	
	textureInfo.mWidth					= Width;
	textureInfo.mHeight					= Height;
	textureInfo.mFormat					= Format;
	textureInfo.mpPixelData				= pPixelDataAlloc;
	textureInfo.mpOutTexture			= &OutTexture;
	++sPendingCreateWriteIndex;
	return true;
}

//=================================================================================================
// HAL DESTROY TEXTURE
// Free up allocated resources tried to a Texture
//=================================================================================================
void HAL_DestroyTexture(ServerTexture& OutTexture)
{
	if( (OutTexture.mpHAL_Texture) && 
		(sPendingDestroyWriteIndex - sPendingDestroyReadIndex >= kPendingCount) )
	{
		sPendingDestroyTextures[(sPendingDestroyWriteIndex++) % kPendingCount] = &OutTexture;
	}
}

}} //namespace NetImguiServer { namespace App

#endif // HAL_API_PLATFORM_GLFW_GL3
```

**Comment by A3Wypiok** [comment]
When creating my window i request an opengl 2 window to glfw but an opengl 3.1 window is created (i used `glGetString(GL_VERSION)` to see the opengl version). That could explain the texture problem (missing backend configuration as you said) but it's strange that the client is correctly rendered using imgui opengl2 backend with opengl 3.1 context.

I have tested your code with opengl 3 and texture is good but i still have a crash when rendering the background, i have to comment this two lines :

```C++
{
    NetImgui::Internal::ScopedImguiContext scopedCtx(client.mpBGContext);
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
}
```

`client.mpBGContext->IO.BackendRendererUserData` is a null pointer but it is used by the imgui opengl3 backend.

As you suggested, i will use opengl 3 for the server.

**Comment by sammyfreg** [comment]
Ah, this might explains it.

Even if you initialize the OpenGL to 3, the Dear ImGui sample code wouldn't know that, and still configure the context backend to 2, creating the incompatibility (in` ImGui_ImplGlfw_Init()` and `ImGui_ImplOpenGLXX_Init()` coming from `imgui_impl_opengl2.cpp` instead of `imgui_impl_opengl3.cpp`).

It would make things simpler to use OpenGL3 with vertex support on the Server, I rely on vertex offset being functional, and if they are not, some change to my server code and the Dear ImGui backend shader code would need to be done for things to work properly. (I only create 1 big vertex/index buffer for the entire frame data to render, using offset into it, by each drawcall).

**Comment by sammyfreg** [comment]
I have updated the dev branch with OpenGL3 support (under Windows).

You can take a look and use that. The `NetImguiServer_HAL_Glfw.cpp` source is missing the Linux implementation, if you're interested in creating a pull request with your Linux changes in it, I'd be happy to take it.

**Comment by sammyfreg** [comment]
I have updated the dev branch with OpenGL3 support (under Windows).

You can take a look and use that. The `NetImguiServer_HAL_Glfw.cpp` source is missing the Linux implementation, if you're interested in creating a pull request with your Linux changes in it, I'd be happy to take it.

**Comment by A3Wypiok** [comment]
Thank you!

I have only implemented ```HAL_GetSocketInfo``` and i don't really know how to implement others (especially ```HAL_ConvertKeyDown```).

```GetCommandLineA``` is a windows function and i don't know how to correctly replace it. As i don't use ```NetImguiServer::App::Startup``` i simply replaced with an empty string.

Additionnaly some functions (```strcpy_s```, ```sprintf_s``` and ```strncpy_s```) must be replaced or something is missing to compile correctly on linux. I was too lazy to investagate this so i just added macro to call the non "_s" version.

**Comment by ozlb** [comment]
Hi, I would like to implement server app in linux with glfw + OpenGL 2. If i understood well, at the end you give up and use GL3?

**Comment by sammyfreg** [comment]
Yes. At the moment the NetImguiServer application needs support for 'vertex' offset in drawcall. It would be possible to modify the codebase to support drawing without offset support, but I don't believe it is worth the effort, given how old this APi is. The server application should be running on a modern PC and doesn't care if the client is using an old rendering API (the client actually doesn't even need any rendering backend at all when using NetImgui)

**Comment by sammyfreg** [comment]
Rendering on the NetImgui Server without 'Vertex Offset' OR 'Index Offset' requires a few changes in  `Client::ConvertToImguiDrawData`.
-Always use 32bits indices (instead of 16bits) for the IndexBuffer
-Output 1 IndexBuffer for each drawing command that use a different starting IndexOffset
-Make sure the Indices written to the IndexBuffer take into account the VertexOffset

**Comment by A3Wypiok** [comment]
If you really need to use opengl 2 backend on the server side then you could try this [patch](https://gist.github.com/A3Wypiok/16af9bd22b8b4e4d60159b02f841b19c).

**Comment by ozlb** [comment]
> If you really need to use opengl 2 backend on the server side then you could try this [patch](https://gist.github.com/A3Wypiok/16af9bd22b8b4e4d60159b02f841b19c).

Thanks!!!

**Comment by sammyfreg** [comment]
It looks like the font texture has not been successfully created on the server side.

**Comment by A3Wypiok** [comment]
The background should be dark grey not totally black. Are you using the `NetImguiServer_HAL_GL3.cpp` and replaced `ImGui_ImplOpenGL3_*` by `ImGui_ImplOpenGL2_*` ?

**Comment by ozlb** [comment]
> The background should be dark grey not totally black. Are you using the `NetImguiServer_HAL_GL3.cpp` and replaced `ImGui_ImplOpenGL3_*` by `ImGui_ImplOpenGL2_*` ?

No, i'm using your `NetImguiServer_HAL_opengl2.cpp` as per https://github.com/sammyfreg/netImgui/issues/20#issue-998246430 
I can't use  `NetImguiServer_HAL_GL3.cpp` and replace GL3 with GL2, i could not compile the project.

**Comment by ozlb** [comment]
> It looks like the font texture has not been successfully created on the server side.

If you mean `Roboto_Medium` font and image background, I removed, but i exclude it's the issue since with GL3 is working properly.

I need GL2 due to the fact that "kiosk stand" systems does not support GL3.

**Comment by sammyfreg** [comment]
No, I meant that Dear ImGui creates a texture with all selected font (even if only the default font is used when not adding any) and then we need to create a texture. This is handled in `HAL_CreateTexture`. It could be that even the RenderTarget hasn't been created  properly by `HAL_CreateRenderTarget` (you can test that by trying to clear the RenderTarget another color. But really, a render capture would be needed to debug it further (with renderdoc).

**Comment by ozlb** [comment]
I'm not so confident, but I will try..
For info both functions are as per https://github.com/sammyfreg/netImgui/issues/20#issue-998246430 `NetImguiServer_HAL_opengl2.cpp`
