### ISSUE TITLE
Can netimgui support X86?

### ISSUE THREAD

**Issue by IULOVE** [sammyfreg/netImgui#34]

**Comment by sammyfreg** [comment]
Certainly.

The NetImgui Client sources (code added to user application) should compile
without any problems.

The NetImgui Server sources should still be able to compile in x86, but I
haven't tested lately. This is not as critical as the client code, since
the server application is meant to run on Windows (or MacOS/Linux with some
additional changes).

**Comment by IULOVE** [comment]
> 
The client can compile X86 but there will be problems with running. I don’t know if you have tried it

**Comment by sammyfreg** [comment]
I just tried the client sample : **SampleBasic** in `clang win32` and `msvc win32` build (those are the 32bits x86 build).  They both were able to run and connect to the **NetImguiServer** compiled in 32 and 64bits.

**Comment by sammyfreg** [comment]
Thank you, this helps a lot.

I will try this repo with the exact same VisualStudio / Windows version. I
also tried with VS2019. Do you know which update you are on?

Once I can reproduce it, should not be difficult to fix.

**Comment by sammyfreg** [comment]
I think I see what your issue is. I fixed it on the 'Dev' branch, but it hasn't been pushed to main in a new release yet.

The simple fix is to add 1 line of code, so the method looks like this :
```
template <typename TType>
void OffsetPointer<TType>::SetPtr(TType* pPointer)
{
	mOffset		= 0; // Remove 'offset flag' that can be left active on non 64bits pointer **** THIS IS IMPORTANT FOR THE 32bits BUG***
	mPointer	= pPointer;
}
```

Or you can use the version from the 'Dev' branch.

**Comment by IULOVE** [comment]
dev no problem, thanks for your answer

**Comment by sammyfreg** [comment]
I will check this later, by compiling one of the samples in x86 in the
coming weeks. Problem should not be too big, probably something to do with
uint64/size_t identifiers.
