### ISSUE TITLE
Auto saving .ini settings of imgui

### ISSUE THREAD

**Issue by lemantisee** [sammyfreg/netImgui#38]
Found some specific bug with autosaving .ini settings file.
I have server and client apps which works from same directory. NetImgui server side in some case will rewrite .ini file from client app. It depends on life cycle, which app will be destroyed first. NetImgui server creates additional imgui context for each client to draw client background (NetImguiServer_App.cpp - DrawClientBackground():131). And on deleting this context in RemoteClient::Client dctor imgui will save .ini file. I fixed for me - just set ImGuiIO::IniFilename to nullptr on context creation.

Is this some specific bug for my case or it's common and we don't need settings file for RemoteClient::Client?

**Comment by sammyfreg** [comment]
It's a good point that I never thought about. I could set each client ini
file to the client name (when they have an associated client config). But
really, the only thing saved is the client tab location, so I might just
set it to null like you did. Simple and I don't see a great benefit from
saving the client tab position.

**Comment by sammyfreg** [comment]
Added change to stop saving to imgui.ini (9e3dc5da7f022621968ab48ea5e819c365f953d3).
