### ISSUE TITLE
NetImGui thinks it's connected when it isn't

### ISSUE THREAD

**Issue by sambonfire** [sammyfreg/netImgui#50]
**Describe the bug**

I noticed that ImGui wasn't drawing in my application, and eventually tracked it down to NetImGui return "true" for IsDrawingRemote.  It seems that this only returns "true" if the API thinks it's connected.

**To Reproduce**
1. Launch application
2. Turn on an imgui menu
3. Notice that it isn't drawing
4. Inspect logs which are printing result if "IsDrawingRemote" - it's true, even though the server isn't turned on.

**Expected behavior**
IsDrawingRemote() only returns true when the server is connected and is drawing.

**Screenshots**
no screen shot

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
The thing I can't explain is that this only happens in a 'release' build of my app, not in debug.  I've checked netstat and i can see my app listening on port 8889 but no connection has been established (in both the working case and broken case).  I'm using a release version of NetImGui in both cases, so I'm not sure what's going on.  When I do connect the remote server, I see my imgui drawing (in both the broken case and working case).

Is there something I can do further to debug this or provide more information?

**Comment by sammyfreg** [comment]
Thanks. If this doesn't happen in debug but happen in debug, my first guess would be that there's a variable that's missing a proper init (debug zero out variable by default, not release).

I currently m unable to investigate this month, but I will take a look when I get my PC back. It should not be too long to fix.

If you wish to investigate it yourself, you can always check what variables are used to return IsDrawingRemote, and see which one might be missing a init after instantiation.

This is after you have called init on NetImgui library, right?

**Comment by sambonfire** [comment]
Hi,

Thanks for the quick response.

I think it must be something in my setup.  I wrote a C binding and it must be mangling the return type somehow (not sure why).  The debugger says that netimgui is returning false (as expected), but for some reason on the other side my code sees it as "true".

I'll close the bug, as this is clearly in my code.

**Comment by sammyfreg** [comment]
I never tested the library under c. You might need to add the C calling convention code to the API header.

Something along these lines (needs to be tested).
```
ifdef __cplusplus
extern "C" {
#endif
 
// normal API function declarations here

#ifdef __cplusplus
}
#endif

```
