### ISSUE TITLE
Input broken with 1.89.9

### ISSUE THREAD

**Issue by sambonfire** [sammyfreg/netImgui#51]
**Describe the bug**
Using ImGui version 1.89.9, the server app seems to be having issues with input.  Specifically, if the mouse if being moved, the mouse position updates properly.  If you stop moving the mouse, the mouse alternates each frame between an invalid position and a valid position.

I did some debugging on the server app, and it seems ok, so my guess is that there is something that's changed with input that the client is not handling properly

This was working properly for us on 1.89.7

**To Reproduce**
1. Use ImGui 1.89.9
2. connect client to server
3. draw a debug gui; its most useful if you output the mouse position somewhere in your gui so you can see it bouncing between valid and invalid values

**Expected behavior**
woudl expect teh mouse position to be consistent, regardless of whether you are moving the mouse or not

**Screenshots**

<img width="311" alt="image" src="https://github.com/sammyfreg/netImgui/assets/26911387/aeef1afc-698a-442f-9644-4c71cc34d795">

![image](https://github.com/sammyfreg/netImgui/assets/26911387/c6aa51d0-f7e2-4a58-ab73-dea45c30a040)

**Desktop (please complete the following information):**

Windows

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sambonfire** [comment]
I think i see what caused this.  In order to update to 1.89.9, I had to switch this line:

https://github.com/sammyfreg/netImgui/blob/35b3e32fbe545357a244cc99c0389d24997ae43f/Code/Client/Private/NetImgui_Api.cpp#L683

to:

```
io.ClearInputKeys();
```

because

```
io.ClearInputCharacters();
```

has been deprecated.

The new method is resetting the mouse position, but clearly the client isn't happy with that.

I'll see if I can find a better fix.

**Comment by sambonfire** [comment]
Im going to try to just switch to this:

```
io.InputQueueCharacters.resize(0);
```

That's what the old method did.

**Comment by sammyfreg** [comment]
Thank you for the detailed report and investigation. I should be able to fix this compatibility issue quickly once I have the chance.
