### ISSUE TITLE
Update rate changes for some reason

### ISSUE THREAD

**Issue by hinxx** [sammyfreg/netImgui#53]
I've added ImPlot to the SampleNoBackend app. While observing the demo plot I noticed that the update rate of the plot changes for some reason. At times it runs normal and at times it runs slower. I do not know what triggers the change in update rate.

I've attached the video. I'm not clicking anywhere (except when scrolling), but just moving my mouse around.

This is with the code from master branch, ImPlot code is also master branch, both as of today.
OS is Linux.
FWIW, Server Configuration is set to refresh Active and Inactive Windows at 60 fps, compression is enabled.
Both Server and Client are on the same host, i.e. there is no network traffic involved - only localhost.

PS. This can also be observed with the ImGui demo with widgets under plotting.

https://github.com/sammyfreg/netImgui/assets/2725009/d074ca10-317f-401b-9194-7abe0e601b35

https://github.com/sammyfreg/netImgui/assets/2725009/7db3aa97-9524-4e95-bddb-5101a68186fe

**Comment by sammyfreg** [comment]
Does it exhibit the same behavior when displayed locally, without using NetImgui. You can verify by adding ImPlot in SampleBasic and see if the behavior is the same between Local draw and when remotely connected.

**Comment by hinxx** [comment]
I'll have to make SampleBasic work on Linux, first. Seems Windows oriented at the moment.

**Comment by sammyfreg** [comment]
Ah, then you might have more luck starting from a Dear ImGui sample directly. That's what all the samples in the folder are,  quick modifications to a Window Dear ImGui sample.

My point is mostly to know if this is just an issue with the NoBackend sample (probably) or a NetImgui performance issue or a NetImgui networking issue.

**Comment by hinxx** [comment]
Using just ImGui glfw/opengl3 example on my machine I see no issues.

**Comment by hinxx** [comment]
I guess what your suggesting is to use original ImGui example that runs on Linux as basis, and add netImgui stuff into it (and not edit existing netImgui Samples).

**Comment by sammyfreg** [comment]
Yes, this is correct. To see if this is NetImgui or just the NoBackend sample. Starting from the Dear ImGui linux sample should be faster than modifying the NetImgui sample. There's not a lot of change needed to make NetImgui work with a Dear ImGui codebase.

**Comment by hinxx** [comment]
I got SampleBasic to work. I see no issues with the rendering rate here.

![Screenshot_2023-11-17_18-00-14](https://github.com/sammyfreg/netImgui/assets/2725009/bdd341c9-e537-4454-a250-c722d0277f20)

**Comment by hinxx** [comment]
What's next to try out?

**Comment by sammyfreg** [comment]
And is the refresh doing ok on the RemoteServer, when connected?

**Comment by hinxx** [comment]
The rate seems still OK, at 60 fps.
(There is something funky with the display.. I'm running this on an older Ubuntu machine at the moment ; I have not seen this on the latest Ubuntu earlier today so it might not be important.)

![Screenshot_2023-11-17_19-55-40](https://github.com/sammyfreg/netImgui/assets/2725009/d15265a5-7a02-4ca1-9753-2a8e61af75de)

**Comment by sammyfreg** [comment]
I wonder if the funkiness is tied to OpenGL drivers issues?

As for your original problem, it would seems that is is simply a problem with the update rate of the NoBackend sample (issue with delta time calculation or limiting the fresh based on time passed?), and probably not something I will investigate much, since it is just there to demonstrate quickly how you can run ImGui remotely without a local display active.

**Comment by hinxx** [comment]
> I wonder if the funkiness is tied to OpenGL drivers issues?

Could be. For some reason it appears only after drawing remotely, though.

> As for your original problem, it would seems that is is simply a problem with the update rate of the NoBackend sample (issue with delta time calculation or limiting the fresh based on time passed?),

I'll see what happens on the newer Ubuntu next week if I tinker with SampleNoBackend code around the sleep..

Thanks!

**Comment by hinxx** [comment]
Now back at the Ubuntu 22.04 machine where the rendering is OK (no more funny looking triangles).

I've removed the lines around the sleep

 https://github.com/sammyfreg/netImgui/blob/master/Code/Sample/SampleNoBackend/SampleNoBackend.cpp#L162-169 

altogether and this is the result. Frame rate is at 60 fps but the updates are always sloooow. The process does consume 100% of one core now, though.

https://github.com/sammyfreg/netImgui/assets/2725009/ac98d70e-79ad-4c53-94fd-add880a05ae6

How would the proper client side with no backend loop look like?

Does this happen for you as well (on Windows?) or is it a Linux issue?

**Comment by sammyfreg** [comment]
You should investigate what's the best method on on Linux to infinitely loop over OS messages, maybe a 'thread yield' would work better than sleep. As for the slow update despite high FPS, this point to maybe the delta time given to ImGui is wrong. In the end, this was really a simple demo framework quickly borrowed from Dear ImGui own samples, I did not spend a lot of time on that aspect beyond integrating NetImgui and adding a sleep in the message loop to prevent high CPU usage.
