### ISSUE TITLE
how to draw image mat (read from opencv) without backend

### ISSUE THREAD

**Issue by zjd1988** [sammyfreg/netImgui#60]
wonderfull work!!! 
I have read a image mat, and want to draw with netimgui without backend, but I google image gui usally need textrue id to draw image (relate to backend).
will you provide some example for me?

**Comment by sammyfreg** [comment]
Hi,

You can look at the SampleTexture project on the NetImgui GitHub to see how
to send a texture to the server and use it to draw.

The current limitation is that only R8 and RGBA8 formats are supported. It
isn't too difficult to add new formats, but it hasn't been done yet.

Le mer. 24 juill. 2024, 21 h 24, zjd1988 ***@***.***> a
écrit :

**Comment by sammyfreg** [comment]
The texture ID can really be anything you want, you just need to upload the
texture with a unique number and it's data, then set the same ID when
drawing your imgui content. To keep things simple, you can just use IDs
starting from 0 and incremented by one for each new texture.

Le mer. 24 juill. 2024, 22 h 14, Sam Registration ***@***.***> a
écrit :

**Comment by zjd1988** [comment]
@sammyfreg Thanks for your reply, I will check SampleTexture project.
![cf568fc4-3829-4d25-ac8d-e555d836016f](https://github.com/user-attachments/assets/5b07118b-52a4-4d2d-bdbb-17b154d3d708)
